[package]
name = "encripter"
version = "0.1.0"
authors = ["Nalbert Gabriel Melo Leal <nalbertgml@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"